version: "3"
volumes:
  idf-test-data-volume:
services:
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db_dump_version_2.sql:/docker-entrypoint-initdb.d/db_dump_version_2.sql
      - idf-test-data-volume:/var/lib/mysql
    ports:
      - "3307:3306"
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"